/* Generated By:JJTree: Do not edit this line. dump.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class dump extends SimpleNode {
  public dump(int id) {
    super(id);
  }

  public dump(FAOPS p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=34e1e074b0fdad7810fba7042a55e460 (do not edit this line) */
