/* Generated By:JJTree: Do not edit this line. Dump.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import org.graphstream.graph.implementations.MultiGraph;
import faops.DumpDot;

public
class Dump extends SimpleNode {
  public Dump(int id) {
    super(id);
  }

  public Dump(FAOPS p, int id) {
    super(p, id);
  }

  public void save() {
      String variableName = ((FA) children[0]).name;
      MultiGraph fa = variables.get(variableName);

      if (fa != null) {
          DumpDot dot = new DumpDot(fa);
          dot.dumpFile(((Path) children[1]).name);
      }
  }

}
/* JavaCC - OriginalChecksum=60817aceaf62609e44b5a471211cb433 (do not edit this line) */
