/* Generated By:JJTree: Do not edit this line. dump.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class dump extends SimpleNode {
  public dump(int id) {
    super(id);
  }

  public dump(FAOPS p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2609ecefb6e09572863cffeca7209402 (do not edit this line) */
