/* Generated By:JJTree: Do not edit this line. expr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class expr extends SimpleNode {
  public expr(int id) {
    super(id);
  }

  public expr(FAOPS p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9c6c58fce0e3db9bc34907ebf6531324 (do not edit this line) */
