/* Generated By:JJTree: Do not edit this line. Expr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import org.graphstream.graph.implementations.MultiGraph;

public
class Expr extends SimpleNode {
  public Expr(int id) {
    super(id);
  }

  public Expr(FAOPS p, int id) {
    super(p, id);
  }

  public MultiGraph eval() throws UndeclaredVariable {
      for (int i = 0; i < children.length; i++) {
          if (children[i] instanceof FA) {
              String variableName = ((FA) children[i]).name;
              MultiGraph fa = variables.get(variableName);

            if (fa != null) {
                return fa;
            } else {
                throw new UndeclaredVariable(variableName);
            }
          } else if (children[i] instanceof Stmt) {
              return ((Stmt) children[i]).eval();
          } else if (children[i] instanceof Op2) {
              MultiGraph operand = ((Stmt) children[i + 1]).eval();
              return ((Op2) children[i]).eval(operand);
          }
      }

      return null;
  }


}
/* JavaCC - OriginalChecksum=73c37595c84010e99372e76b018a4400 (do not edit this line) */
