/* Generated By:JJTree: Do not edit this line. Expr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Expr extends SimpleNode {
  public Expr(int id) {
    super(id);
  }

  public Expr(FAOPS p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=73c37595c84010e99372e76b018a4400 (do not edit this line) */
