/* Generated By:JJTree: Do not edit this line. expr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class expr extends SimpleNode {
  public expr(int id) {
    super(id);
  }

  public expr(FAOPS p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2c9d4882b6c33d7b57dd27e1ee2eb8a3 (do not edit this line) */
