/* Generated By:JJTree&JavaCC: Do not edit this line. FAOPSConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FAOPSConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FA = 4;
  /** RegularExpression Id. */
  int FANAME = 5;
  /** RegularExpression Id. */
  int QUOTES = 6;
  /** RegularExpression Id. */
  int FILENAME = 7;
  /** RegularExpression Id. */
  int MULTIPLY = 8;
  /** RegularExpression Id. */
  int CONCATENATE = 9;
  /** RegularExpression Id. */
  int INTERSECTION = 10;
  /** RegularExpression Id. */
  int UNION = 11;
  /** RegularExpression Id. */
  int COMPLEMENT = 12;
  /** RegularExpression Id. */
  int REVERSE = 13;
  /** RegularExpression Id. */
  int NEW = 14;
  /** RegularExpression Id. */
  int DUMP = 15;
  /** RegularExpression Id. */
  int ASSIGN = 16;
  /** RegularExpression Id. */
  int BEGINOPERATION = 17;
  /** RegularExpression Id. */
  int ENDOPERATION = 18;
  /** RegularExpression Id. */
  int ENDLINE = 19;
  /** RegularExpression Id. */
  int LF = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"FA\"",
    "<FANAME>",
    "\"\\\"\"",
    "<FILENAME>",
    "\"x\"",
    "\".\"",
    "\"int\"",
    "\"+\"",
    "\"not(\"",
    "\"rev(\"",
    "\"new(\"",
    "\".dump(\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "<LF>",
  };

}
