/* Generated By:JavaCC: Do not edit this line. FAOPSTreeConstants.java Version 7.0.2 */
public interface FAOPSTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTMT = 1;
  public int JJTVARIABLE = 2;
  public int JJTPATH = 3;
  public int JJTEXPR = 4;
  public int JJTOP1 = 5;
  public int JJTOP2 = 6;
  public int JJTDUMP = 7;


  public String[] jjtNodeName = {
    "start",
    "stmt",
    "variable",
    "path",
    "expr",
    "op1",
    "op2",
    "dump",
  };
}
/* JavaCC - OriginalChecksum=8919ae0f504ce28d0a1aecfd39cb3870 (do not edit this line) */
