/* Generated By:JavaCC: Do not edit this line. FAOPSTreeConstants.java Version 7.0.2 */
public interface FAOPSTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTMT = 1;
  public int JJTEXPR = 2;
  public int JJTOP1 = 3;
  public int JJTOP2 = 4;
  public int JJTDUMP = 5;


  public String[] jjtNodeName = {
    "start",
    "stmt",
    "expr",
    "op1",
    "op2",
    "dump",
  };
}
/* JavaCC - OriginalChecksum=b2829edbaa9e578538a85214486aca30 (do not edit this line) */
