/* Generated By:JavaCC: Do not edit this line. FAOPSTreeConstants.java Version 5.0 */
public interface FAOPSTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTMT = 1;
  public int JJTVARIABLE = 2;
  public int JJTPATH = 3;
  public int JJTEXPR = 4;
  public int JJTOP1 = 5;
  public int JJTOP2 = 6;
  public int JJTDUMP = 7;


  public String[] jjtNodeName = {
    "start",
    "stmt",
    "variable",
    "path",
    "expr",
    "op1",
    "op2",
    "dump",
  };
}
/* JavaCC - OriginalChecksum=c978e97bef55fc04c107e06c5e87d98d (do not edit this line) */
