/* Generated By:JJTree: Do not edit this line. Op1.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Op1 extends SimpleNode {
    public int op = -1;
    public String[] operations = {"multiply", "concatenate", "intersection", "union"};
  public Op1(int id) {
    super(id);
  }

  public Op1(FAOPS p, int id) {
    super(p, id);
  }

  public String toString() { return FAOPSTreeConstants.jjtNodeName[id] + " " + operations[op]; }

}
/* JavaCC - OriginalChecksum=ba6b37bffa95f3766b450265075b1532 (do not edit this line) */
