/* Generated By:JJTree: Do not edit this line. op1.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class op1 extends SimpleNode {
  public op1(int id) {
    super(id);
  }

  public op1(FAOPS p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=277178ac68b0e071eda623d3fb502080 (do not edit this line) */
