/* Generated By:JJTree: Do not edit this line. Op2.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import org.graphstream.graph.implementations.MultiGraph;
import faops.Reverse;
import faops.Complement;

public
class Op2 extends SimpleNode {
    public int op = -1;
    public String[] operations = {"complement", "reverse"};
  public Op2(int id) {
    super(id);
  }

  public Op2(FAOPS p, int id) {
    super(p, id);
  }

  public MultiGraph eval(MultiGraph graph) {
     if (op == 0) {
         Complement complementer = new Complement(graph);
         return complementer.getGraph();
     }
     else if (op == 1) {
           Reverse reverser = new Reverse(graph);
           return reverser.getReversed();
       }

      return null;
  }

    public String toString() { return FAOPSTreeConstants.jjtNodeName[id] + " " + operations[op]; }
}
/* JavaCC - OriginalChecksum=8a6d323e32140b80191bef670bc4aae5 (do not edit this line) */
