/* Generated By:JJTree: Do not edit this line. Op2.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Op2 extends SimpleNode {
    public int op = -1;
    public String[] operations = {"complement", "reverse"};
  public Op2(int id) {
    super(id);
  }

  public Op2(FAOPS p, int id) {
    super(p, id);
  }

    public String toString() { return FAOPSTreeConstants.jjtNodeName[id] + " " + operations[op]; }
}
/* JavaCC - OriginalChecksum=8a6d323e32140b80191bef670bc4aae5 (do not edit this line) */
