/* Generated By:JJTree: Do not edit this line. path.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class path extends SimpleNode {
    String name = null;
  public path(int id) {
    super(id);
  }

  public path(FAOPS p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9c28486dcd8a9f38d681940eccf4fba2 (do not edit this line) */
