/* Generated By:JJTree: Do not edit this line. Path.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class Path extends SimpleNode {
    String name = null;
  public Path(int id) {
    super(id);
  }

  public Path(FAOPS p, int id) {
    super(p, id);
  }
    public String toString() { return FAOPSTreeConstants.jjtNodeName[id] + " " + name; }

}
/* JavaCC - OriginalChecksum=21a6e1fe5121be35b4a82bd5af0a0ef6 (do not edit this line) */
