/* Generated By:JJTree: Do not edit this line. start.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class start extends SimpleNode {
  public start(int id) {
    super(id);
  }

  public start(FAOPS p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f5784ee2a59b62980e3960ccd16ac64a (do not edit this line) */
