/* Generated By:JJTree: Do not edit this line. start.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class start extends SimpleNode {
  public start(int id) {
    super(id);
  }

  public start(FAOPS p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f659109abd1669a5a363c83ab8f9f5da (do not edit this line) */
