/* Generated By:JJTree: Do not edit this line. stmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class stmt extends SimpleNode {

  public stmt(int id) {
    super(id);
  }

  public stmt(FAOPS p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c860cbdd25d01403ac1c3acb0073d5d7 (do not edit this line) */
