/* Generated By:JJTree: Do not edit this line. variable.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class variable extends SimpleNode {
    public String name = null;
  public variable(int id) {
    super(id);
  }

  public variable(FAOPS p, int id) {
    super(p, id);
  }

  public String toString() { return FAOPSTreeConstants.jjtNodeName[id] + " " + name; }

}
/* JavaCC - OriginalChecksum=4de487d321f9f97c784bb1c4a7729716 (do not edit this line) */
