/* Generated By:JJTree: Do not edit this line. FA.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class FA extends SimpleNode {
    public String name = null;

    public FA(int id) {
    super(id);
    }

    public FA(FAOPS p, int id) {
    super(p, id);
    }

    public String toString() { return FAOPSTreeConstants.jjtNodeName[id] + " " + name; }

}
/* JavaCC - OriginalChecksum=4431d85b289545faf69d7fdd3c9b117e (do not edit this line) */
