/* Generated By:JavaCC: Do not edit this line. FAOPSTreeConstants.java Version 7.0.2 */
public interface FAOPSTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTMT = 1;
  public int JJTFA = 2;
  public int JJTPATH = 3;
  public int JJTEXPR = 4;
  public int JJTOP1 = 5;
  public int JJTOP2 = 6;
  public int JJTDUMP = 7;


  public String[] jjtNodeName = {
    "Start",
    "Stmt",
    "FA",
    "Path",
    "Expr",
    "Op1",
    "Op2",
    "Dump",
  };
}
/* JavaCC - OriginalChecksum=8e8985a3aac2d3dae0c073a0955dc537 (do not edit this line) */
